### ISSUE TITLE
Packaged app (Mac OS) is damaged and can't be opened

### ISSUE THREAD

**Issue by jayczech23** [AndyObtiva/glimmer-dsl-swt#13]
**Desktop (please complete the following information and make sure it matches [Glimmer Pre-Requisites](https://github.com/AndyObtiva/glimmer-dsl-swt#pre-requisites) before reporting an issue):**
 -Mac OS 11.2.1 (Big Sur)
 - Java Version: 16.0.2
 - JRuby Version: 9.3.0.0 (2.6.8)
 - Glimmer Libraries/Versions:  glimmer-dsl-swt 4.21.1.0

**Describe the issue**
After creating an application with scaffolding, when I got to run `glimmer package[dmg]` on MacOS, and distribute the created artifact to users/testers, they get an error when attempting to run the dmg file after installation:

``` NAME.app is damaged and can't be opened. You should move it to the trash```

**Comment by AndyObtiva** [comment]
Thank you for reporting this issue.

Firstly, I just updated README.md to note that Glimmer DSL for SWT has been upgraded already to jruby-9.3.1.0 (it can install more easily on Windows by resolving an issue with the 9.3.0.0 Windows installer)

Next, about your issue, I've seen it before. It happens when distributing a Mac native executable packaged from a platform incompatible with the other user's platform.

To get around that, make sure to repackage the app from a matching OS and Processor Architector to the end-user. For example, if they are going to use the app on a Mac Intel x64 running Catalina, repackage the app on that exact syste and distribute to them.

What I observed is usually if you package from the most modern system possible (e.g. Big Sur x86_64), it will work on all previous platforms given the same CPU architecture (x86_64). That said, I encountered issues with Big Sur packages not working on Catalina before, so simply repackage as indicated above, and that should resolve the issue.

Please let me know if that works for you.

**Comment by jayczech23** [comment]
Hi @AndyObtiva, thank you for the prompt reply.

I have verified that I was using a MacOS version that was older than the ones my testers are using, so I will update my OS and repackage and post the result here.

It just so happens that the machine I am trying to package Windows builds on uses ARM64, I have opened a separate ticket here:

 #14

**Comment by AndyObtiva** [comment]
I am glad you have a path of action towards a solution.

Is your system ARM64 or AMD64? I am only asking to be sure since you mentioned AMD64 on the Windows issue (#14). AMD64 is actually the same as X86_64 or X64. ARM64 is the same as AArch64, which is different from AMD64.

**Comment by jayczech23** [comment]
The Mac I am using to package Mac apps is `X86_64`. 

The Windows machine I am using is `AMD64` 

Thanks for pointing the difference out!

**Comment by jayczech23** [comment]
@AndyObtiva 

I have updated `glimmer-dsl-swt` to `4.21.2.0` and have rebuilt a scaffold. Able to run the app on my machine using `glimmer run`, but still encountering the `App is Damaged and cannot be opened` when packaging as `.dmg` file and distributing for testing.

**Comment by AndyObtiva** [comment]
I don't know about Monterey since it is too new still. For example, this article says [it is breaking some Macs](https://appleinsider.com/articles/21/11/02/macos-monterey-may-be-bricking-some-macs---but-there-is-a-fix).

That said, what I suggested earlier is that you find an identical machine to your end-users' (or replicate their machine via virtualization if you can't.. e.g. [Install Catalina in VirtualBox](https://blog.victormendonca.com/2020/04/17/how-to-install-macos-catalina-in-virtual-box/))

Are your users using Monterey on the same exact CPU architecture that you have? If not, what OS are they using? You might have to build multiple packages for each series of machines. In the older days, I remember Catalina packages working on Mojave and High Sierra. Nowadays, it seems Big Sur packages are hit or miss when it comes to running on Catalina. I don't know anything about Monterey at all, but could attempt to help if really needed. My brother works for Apple.

Cheers.

**Comment by AndyObtiva** [comment]
Hi, I'd just like to note that I tried packaging on Monterey and then attempting to run the package on Catalina, and it indeed does not work and tells me to move to the Trash.

Again, this is in line with the recommendation I made about packaging for each platform on the same platform since Big Sur came out. (Catalina packages do run on Mojave and High Sierra in my experience though)

Cheers.

**Comment by AndyObtiva** [comment]
More news.

I tried installing a Big-Sur-packaged Glimmer DSL for SWT app (https://github.com/AndyObtiva/glimmer_tetris) on an M1 Chip Mac with Monterey that has [Rosetta ARM64-to-X64 translator](https://support.apple.com/en-us/HT211861) installed.

It worked! (you can try it yourself)

First of all, I got this message box (understandable since I did not sign my app with Apple):
![Screen Shot 2022-01-18 at 8 45 47 AM](https://user-images.githubusercontent.com/23052/149949896-c3020447-d6e7-41bc-853e-9bd83e1750d9.png)

Next, I went to System Preferences -> Security & Privacy -> General Tab and saw this message about Glimmer Tetris app:
![Screen Shot 2022-01-18 at 8 46 09 AM](https://user-images.githubusercontent.com/23052/149949988-7df52ac6-7459-4147-84c1-97b172cd3262.png)

I clicked Open Anyway:
![Screen Shot 2022-01-18 at 8 46 15 AM](https://user-images.githubusercontent.com/23052/149950031-fbd6d977-bd96-4af8-84ee-faaa4d550a77.png)

Finally, I clicked Open and BOOM, Tetris was working (though keep in mind that due to JVM/JRuby, it is a bit slow to start):
![Screen Shot 2022-01-18 at 8 46 53 AM](https://user-images.githubusercontent.com/23052/149950061-0002995c-eaf6-461c-8164-5da7c6445274.png)

Maybe you could share similar instructions with some of your users unless you decide to [sign (notarize) your app with Apple](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md#mac-application-distribution).

**Comment by AndyObtiva** [comment]
BTW, I finally got around to testing [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) with ARM64/AARCH64. Version 4.22.2.1 officially supports ARM64/AARCH64 on Mac and Linux.

Cheers!

**Comment by AndyObtiva** [comment]
I discovered one more possible cause of your issue. Apparently, if you package an application on a specific version of a MacOS (e.g. Big Sur 11.5.0) and distribute it to users who just downloaded the latest OS Updates for Big Sur (e.g. Big Sur 11.6.5), thus reaching a higher revision of Big Sur than the one that you packaged the app on, then the binary file might end up becoming incompatible, and thus might display the "Damaged" message.

The solution is as simple as updating your OS to the latest revision that matches the users' and then repackaging the app. 

It's a bit sad that MacOSs in later years have become incompatible with each other (it was not an issue before Catalina) and in some cases incompatible with the same MacOS having a different revision. I bet binaries created using XCode would suffer the same fate in those scenarios, and the solution is always to repackage your app for the latest MacOS revision that matches the users'.

If the mentioned solution resolves your problem, please let me know so I'd close this GitHub issue.

Cheers!

**Comment by jayczech23** [comment]
Hi @AndyObtiva 

Thanks for looking into this issue and for the prompt responses!

I have not tried running glimmer since my last reply, as we have switched to implementing with ElectronJS.

I will try to get around to testing on my updated M1 Macbook soon, and will let you know if the issue is resolved!

Thanks again!
